name: Extract Tables from PDFs

on:
  push:
    branches:
      - main

jobs:
  extract-tables:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: pip install pdfminer.six
      - name: Extract Tables from PDF
        run: | 
          python -m pdfminer.six.pdfparser input.pdf > output.csv 
          #  replace 'input.pdf' with your PDF file 
          #  adjust 'output.csv' if you want a different output format
